### ISSUE TITLE
Personnal update notification

### ISSUE THREAD

**Issue by A-d-r-i** [A-d-r-i/update_choco_package#11]
Add in `PACKAGENAME.yml`
```yml
      - name: Script
        env:
          TELEGRAM: ${{ secrets.TELEGRAM }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
```

Add in `send_PACKAGENAME.ps1` :
```sh
#send telegram notification
Function Send-Telegram {
Param([Parameter(Mandatory=$true)][String]$Message)
$Telegramtoken = "$env:TELEGRAM"
$Telegramchatid = "$env:CHAT_ID"
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
$Response = Invoke-RestMethod -Uri "https://api.telegram.org/bot$($Telegramtoken)/sendMessage?chat_id=$($Telegramchatid)&text=$($Message)"}

Send-Telegram -Message "[UCP] New update of PACKAGENAME : $tag"
```
